##############################################################################
##############################################################################
#
# NOTE!
#
# Please read the README.md file in this directory that defines what should 
# be placed in this file
#
##############################################################################
##############################################################################

name: Issues Workflow
on:
  issues:
    types: ['opened']

permissions:
  issues: write
  pull-requests: write
  
jobs:
  Opened-issue-label:
    name: Adding Issue Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['unapproved']
            })
  
  Issue-Greeting:
    name: Greeting Message to User
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thank you for opening this issue! 🚀 Our team will review it soon. Please make sure you've included all relevant details and followed our [Contributing Guidelines](https://github.com/may-tas/TextEditingApp/blob/main/CONTRIBUTING.md). For questions about our project, check out our [README](https://github.com/may-tas/TextEditingApp/blob/main/README.md) and [Code of Conduct](https://github.com/may-tas/TextEditingApp/blob/main/CODE_OF_CONDUCT.md)."
            })