name: PR Target Workflow

on: 
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  PR-Greeting:
    name: Pull Request Target
    runs-on: ubuntu-latest
    steps:
      - name: Add the PR Review Policy
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: pr_review_policy
          message: |
            ## Our Pull Request Approval Process

            Thanks for contributing! 

            ### Reviewers

            Do not assign reviewers. Our Queue Monitors will review your PR and assign them. 
            When your PR has been assigned reviewers contact them to get your code reviewed and approved via:

            1. comments in this PR

            #### Reviewing Your Code

            Your reviewer(s) will have the following roles:

            1.  arbitrators of future discussions with other contributors about the validity of your changes
            2.  point of contact for evaluating the validity of your work
            3.  person who verifies matching issues by others that should be closed.
            4.  person who gives general guidance in fixing your tests

            ## Other

            :dart: Please be considerate of our volunteers' time. Contacting the person who assigned the reviewers is not advised unless they ask for your input. Do not @ the person who did the assignment otherwise.

      - name: Greeting Message to User
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: "🎉 Congratulations on making your first PR! If you haven't already, check out our [Contributing Guidelines](https://github.com/may-tas/TextEditingApp/blob/main/CONTRIBUTING.md) and [README](https://github.com/may-tas/TextEditingApp/blob/main/README.md) to ensure that you are following our guidelines for contributing."